version: '3.8'
services:
  postgres:
    container_name: postgres-scheduler
    image: postgres:latest
    environment:
      POSTGRES_DB: schedulerms
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: